// packages/angular/src/index.ts
import { Injectable, NgModule } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';
import {
  apiRequest,
  ApiRequestOptions,
  initPlatform,
  getContextObservable,
  getThemeObservable,
} from 'widget-sdk-core';

@Injectable({ providedIn: 'root' })
export class PlatformService {
  private _context$ = new BehaviorSubject<any>(null);
  private _theme$ = new BehaviorSubject<any>(null);
  private _initialized = false;

  async apiRequest(req: ApiRequestOptions) {
    return apiRequest(req);
  }

  /**
   * Initialize the platform service. Must be called before using observables.
   * For shadow DOM scenarios, pass the element.
   */
  async initialize(ctx?: { element?: HTMLElement }): Promise<void> {
    if (this._initialized) return;

    try {
      await initPlatform(ctx);

      // Subscribe to core observables
      const [contextObs, themeObs] = await Promise.all([
        getContextObservable(),
        getThemeObservable(),
      ]);

      // Subscribe to context changes
      contextObs.subscribe((context: any) => {
        this._context$.next(context);
      });

      // Subscribe to theme changes
      themeObs.subscribe((theme: any) => {
        this._theme$.next(theme);
      });

      this._initialized = true;
    } catch (error) {
      throw error;
    }
  }

  /**
   * Observable stream of context changes
   */
  get context$(): Observable<any> {
    return this._context$.asObservable();
  }

  /**
   * Observable stream of theme changes
   */
  get theme$(): Observable<any> {
    return this._theme$.asObservable();
  }

  /**
   * Get current context value
   */
  get currentContext(): any {
    return this._context$.value;
  }

  /**
   * Get current theme value
   */
  get currentTheme(): any {
    return this._theme$.value;
  }

  /**
   * Check if the service has been initialized
   */
  get isInitialized(): boolean {
    return this._initialized;
  }
}

@NgModule({
  providers: [PlatformService],
})
export class PlatformModule {}

// packages/react/src/index.tsx
import React, { createContext, useContext, useEffect, useState } from 'react';
import {
  apiRequest,
  initPlatform,
  getPlatformElement,
  getContextObservable,
  getThemeObservable,
} from 'widget-sdk-core';

type PlatformState = {
  context: any;
  theme: any;
  element: HTMLElement | null;
};

const PlatformContext = createContext<any>(null);

export function PlatformProvider({
  children,
  element,
}: {
  children: React.ReactNode;
  element?: HTMLElement;
}) {
  const [state, setState] = useState<PlatformState>({
    context: null,
    theme: null,
    element: null,
  });

  useEffect(() => {
    let contextUnsubscribe: (() => void) | null = null;
    let themeUnsubscribe: (() => void) | null = null;

    async function init() {
      try {
        // Initialize platform
        await initPlatform(element ? { element } : undefined);

        // Subscribe to context and theme observables
        const [contextObs, themeObs] = await Promise.all([
          getContextObservable(),
          getThemeObservable(),
        ]);

        // Subscribe to changes
        contextUnsubscribe = contextObs.subscribe((context: any) => {
          setState(prevState => ({ ...prevState, context }));
        });

        themeUnsubscribe = themeObs.subscribe((theme: any) => {
          setState(prevState => ({ ...prevState, theme }));
        });

        // Set platform element
        setState(prevState => ({
          ...prevState,
          element: getPlatformElement(),
        }));
      } catch (error) {}
    }

    init();

    // Cleanup on unmount
    return () => {
      contextUnsubscribe?.();
      themeUnsubscribe?.();
    };
  }, [element]);

  return (
    <PlatformContext.Provider value={{ ...state, apiRequest }}>
      {children}
    </PlatformContext.Provider>
  );
}

export function usePlatform() {
  return useContext(PlatformContext);
}

export default PlatformProvider;
